import type { Agent } from "./types";

/**
 * Eleven agents, one brain. The agent names exist for navigation, billing and
 * colour-coding — never for conversation. Only Emory speaks.
 */
export const AGENTS: Agent[] = [
  {
    id: "audit",
    name: "Emory Audit",
    short: "Audit",
    line: "Tells you what's broken and what it's costing you.",
    hex: "#4A5568",
    onColor: "dark",
    wave: 1,
    status: "live",
    capabilities: [
      "Website health — speed, mobile, broken links, redirects",
      "Content inventory — every page, what it targets, what it is missing",
      "Machine-readable check — how AI tools read your business",
      "Platform detection — so the right connection is offered",
      "Health score and ranked gap report",
    ],
    tiers: [
      { name: "Free", price: "Free", includes: "Everything. No signup, no card, no call." },
    ],
    metered: "Nothing. Audit is the front door and is never monetised.",
  },
  {
    id: "scout",
    name: "Emory Scout",
    short: "Scout",
    line: "Watches everyone you compete with, continuously.",
    hex: "#2F6B3F",
    onColor: "dark",
    wave: 1,
    status: "live",
    capabilities: [
      "Finds who actually competes for the same customers",
      "What they cover that you do not",
      "Whether AI assistants recommend them over you, and why",
      "Every ad they are running, from public ad libraries",
      "How they present, price and differentiate",
    ],
    tiers: [
      { name: "Starter", price: "$29", includes: "3 competitors, monthly refresh" },
      { name: "Growth", price: "$69", includes: "8 competitors, weekly refresh, AI visibility, ad intelligence" },
      { name: "Scale", price: "$139", includes: "20 competitors, daily refresh, pricing intelligence, alerts" },
    ],
    metered: "Competitors tracked, refresh rate",
  },
  {
    id: "beacon",
    name: "Emory Beacon",
    short: "Beacon",
    line: "Makes you findable everywhere people look.",
    hex: "#FF6B1A",
    onColor: "light",
    wave: 1,
    status: "live",
    capabilities: [
      "Getting found in search — page titles, descriptions, structure, internal links",
      "Getting recommended by AI assistants",
      "Answering the questions people actually ask",
      "Business profile — categories, hours, photos, posts, map position",
      "Directories and listings",
      "Reviews — requests, replies, sentiment",
      "Making your catalogue readable to AI shopping tools",
    ],
    tiers: [
      { name: "Starter", price: "$69", includes: "1 location, 100 pages, 50 tracked terms" },
      { name: "Growth", price: "$139", includes: "3 locations, 500 pages, 200 terms, AI visibility tracking" },
      { name: "Scale", price: "$249", includes: "Unlimited locations and pages, directories, reviews" },
    ],
    metered: "Locations, pages, tracked terms",
  },
  {
    id: "write",
    name: "Emory Write",
    short: "Write",
    line: "Writes every word you publish.",
    hex: "#3A3A3D",
    onColor: "dark",
    wave: 2,
    status: "activating",
    activating: "Activating March",
    capabilities: [
      "Pages and articles, written against a gap Scout or Beacon found",
      "Comparison and integration pages",
      "Social copy and publishing",
      "Comment and message replies in your voice, delivered by Envoy",
      "Email and newsletter copy",
      "Additional languages where your revenue is",
    ],
    tiers: [
      { name: "Starter", price: "$59", includes: "4 long pieces, 12 social posts, 1 language" },
      { name: "Growth", price: "$119", includes: "10 long pieces, 40 social posts, 2 languages, publishing" },
      { name: "Scale", price: "$199", includes: "25 long pieces, 120 social posts, unlimited languages" },
    ],
    metered: "Pieces, posts, languages",
  },
  {
    id: "studio",
    name: "Emory Studio",
    short: "Studio",
    line: "Builds everything visual, and everything that converts.",
    hex: "#F5C400",
    onColor: "light",
    wave: 2,
    status: "activating",
    activating: "Activating April",
    capabilities: [
      "Campaign landing pages, hosted and measured",
      "Lead magnets, calculators and forms",
      "Ad images, social graphics, product cards",
      "Short video, metered with a visible allowance",
      "Variants of a winning angle for testing",
    ],
    tiers: [
      { name: "Starter", price: "$49", includes: "3 videos, 20 statics, 1 landing page" },
      { name: "Growth", price: "$99", includes: "10 videos, 60 statics, 4 pages, 2 lead magnets" },
      { name: "Scale", price: "$199", includes: "25 videos, 150 statics, unlimited pages and magnets" },
    ],
    metered: "Videos, statics, pages. Overage priced before generation, never unlimited.",
  },
  {
    id: "media",
    name: "Emory Media",
    short: "Media",
    line: "Runs your ads, and decides where the money should go.",
    hex: "#1B6FD4",
    onColor: "dark",
    wave: 2,
    status: "activating",
    activating: "Activating April",
    capabilities: [
      "Google Ads — structure, keywords, negatives, bids",
      "Meta Ads — structure, audiences, placements, budget",
      "Every word inside your ad accounts",
      "Retargeting and audience building",
      "Budget allocation, including telling you to spend less",
      "Creative testing: hypothesis, variant, result, next hypothesis",
    ],
    tiers: [
      { name: "Starter", price: "$69", includes: "1 platform, up to $5k monthly ad spend managed" },
      { name: "Growth", price: "$139", includes: "Both platforms, up to $25k spend, retargeting, creative testing" },
      { name: "Scale", price: "$229 + 3%", includes: "Unlimited platforms, 3% of spend above $25k, capped" },
    ],
    metered: "Ad spend managed",
  },
  {
    id: "envoy",
    name: "Emory Envoy",
    short: "Envoy",
    line: "Answers every customer, on every channel, instantly.",
    hex: "#0E9AA7",
    onColor: "dark",
    wave: 1,
    status: "live",
    capabilities: [
      "Website chat that knows what you sell and what it costs",
      "WhatsApp, through an existing provider",
      "Instagram and Facebook messages, treated as leads",
      "Email, inbound and outbound",
      "Text and voice, from Wave 3",
      "Meeting booking, confirmations and reminders",
    ],
    tiers: [
      { name: "Starter", price: "$49", includes: "Chat and WhatsApp, 500 conversations" },
      { name: "Growth", price: "$89", includes: "Adds messages, email, booking, 2,000 conversations" },
      { name: "Scale", price: "$179", includes: "Adds text, voice and missed-call, 6,000 conversations" },
    ],
    metered: "Conversations and channels. Provider fees pass through at cost.",
  },
  {
    id: "forge",
    name: "Emory Forge",
    short: "Forge",
    line: "Turns conversations into revenue, and chases what stalls.",
    hex: "#B23A28",
    onColor: "dark",
    wave: 1,
    status: "live",
    capabilities: [
      "Connects to the CRM you already pay for, or gives you one",
      "Tells you which leads are worth your time today, with a value",
      "Chases the enquiries that went quiet",
      "Quotes, proposals and payment links",
      "Win-back and repeat purchase",
    ],
    tiers: [
      { name: "Starter", price: "$59", includes: "CRM connection, scoring, 1,000 contacts" },
      { name: "Growth", price: "$99", includes: "Adds follow-ups, payment links, recovery, 5,000 contacts" },
      { name: "Scale", price: "$179", includes: "Adds native CRM, quotes, win-back, 25,000 contacts" },
    ],
    metered: "Contacts and capabilities",
  },
  {
    id: "hunt",
    name: "Emory Hunt",
    short: "Hunt",
    line: "Goes and finds demand instead of waiting for it.",
    hex: "#6B3FA0",
    onColor: "dark",
    wave: 3,
    status: "activating",
    activating: "Activating September",
    capabilities: [
      "Finds and enriches prospects matching your best customers",
      "Named-account outreach across channels",
      "Referral and affiliate programmes",
      "Creator and partner outreach",
    ],
    tiers: [
      { name: "Starter", price: "$69", includes: "Referral programme, 200 prospects a month" },
      { name: "Growth", price: "$139", includes: "Adds sequencing and enrichment, 1,000 prospects" },
      { name: "Scale", price: "$229", includes: "Adds named accounts and creator outreach, 4,000 prospects" },
    ],
    metered: "Prospects contacted. Contact data billed at cost.",
  },
  {
    id: "ledge",
    name: "Emory Ledge",
    short: "Ledge",
    line: "Tells you what actually worked, and what to do next.",
    hex: "#24386B",
    onColor: "dark",
    wave: 1,
    status: "live",
    capabilities: [
      "Works out where customers really came from, including AI answers",
      "One person, one timeline, across every channel",
      "One revenue number you can trust",
      "Holdout and region tests, because clicks no longer tell the truth",
      "The monthly Proof report",
    ],
    tiers: [
      { name: "Starter", price: "$49", includes: "Core attribution, one revenue view" },
      { name: "Growth", price: "$89", includes: "Adds experiments, cohorts, Proof report" },
      { name: "Scale", price: "$169", includes: "Adds call intelligence, LTV, forecasting" },
    ],
    metered: "Channels and experiment depth",
  },
  {
    id: "guard",
    name: "Emory Guard",
    short: "Guard",
    line: "Stops you publishing something that gets you fined.",
    hex: "#6B1218",
    onColor: "dark",
    wave: 1,
    status: "live",
    capabilities: [
      "Permission captured per person, per channel, with a trail",
      "Privacy obligations by country",
      "Do-not-contact and opt-out, honoured everywhere at once",
      "Claim checks that run before anything is written",
      "A log of everything published and who approved it",
    ],
    tiers: [
      { name: "Included", price: "Included", includes: "Free with every paid agent. Never sold separately, never optional." },
    ],
    metered: "Never metered.",
  },
];

export const AGENT_BY_ID = Object.fromEntries(
  AGENTS.map((agent) => [agent.id, agent]),
) as Record<Agent["id"], Agent>;

export const COMPLETE_PRICING = [
  {
    stage: "Launch",
    price: "$229",
    justifies:
      "All eleven agents at Growth tier. Wave 1 capabilities live, the rest activating on schedule.",
  },
  {
    stage: "Platform",
    price: "$399",
    justifies:
      "Write, Studio, Media and reputation fully live. Replaces the agency retainer, not just the tooling.",
  },
  {
    stage: "Complete",
    price: "$529",
    justifies:
      "Voice, outbound and full attribution. Replaces the person answering enquiries as well.",
  },
];

/** Their line items, their total, our price. Never a percentage. */
export const REPLACEMENT_LINES = [
  { label: "Marketing generalist, one hire", amount: 3200, replacedBy: "Beacon, Write, Media, Ledge" },
  { label: "Content and design freelancers", amount: 1200, replacedBy: "Write, Studio" },
  { label: "Ads freelancer or small agency", amount: 900, replacedBy: "Media" },
  { label: "CRM", amount: 180, replacedBy: "Forge, or connected and kept" },
  { label: "Email and lifecycle", amount: 150, replacedBy: "Envoy, Forge" },
  { label: "Search tooling", amount: 130, replacedBy: "Beacon, Scout" },
  { label: "Chat and support", amount: 99, replacedBy: "Envoy" },
  { label: "Knowing what worked", amount: 0, replacedBy: "Ledge", absent: true },
  { label: "Compliance review", amount: 0, replacedBy: "Guard", absent: true },
];
