export const NAV_ITEMS = [
  {
    index: "01",
    href: "/feed",
    label: "The Feed",
    short: "Feed",
    standfirst: "Dispatches awaiting your desk",
    icon: "newspaper",
  },
  {
    index: "02",
    href: "/strategy",
    label: "Strategy Room",
    short: "Strategy",
    standfirst: "Positioning, voice and the plan",
    icon: "file-text",
  },
  {
    index: "03",
    href: "/seo",
    label: "SEO Audit",
    short: "Audit",
    standfirst: "What the crawl turned up",
    icon: "search",
  },
  {
    index: "04",
    href: "/integrations",
    label: "Wire Room",
    short: "Wire",
    standfirst: "Sources feeding the desks",
    icon: "link",
  },
  {
    index: "05",
    href: "/profile",
    label: "Company Profile",
    short: "Profile",
    standfirst: "Who we file for",
    icon: "target",
  },
] as const;
